model:
  base_learning_rate: 5.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: cond
    image_size: 64
    channels: 4
    cond_stage_trainable: false
    concat_mode: true
    monitor: val/loss
    grad_corr_weight: 1.0e-4
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 12 # 4 Latent + 8 Condition
        out_channels: 4
        model_channels: 128
        attention_resolutions:
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        - 4
        num_head_channels: 32
        dropout: 0.1
        use_wavelet: true
    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ckpt_path: logs/2026-02-01T00-29-11_autoencoder_kl_32x32x4/checkpoints/epoch=000092.ckpt
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 504
          in_channels: 1
          out_ch: 1
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      target: torch.nn.Identity

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 16
    num_workers: 8
    wrap: false
    train:
      target: ldm.data.cfd_data.CFDConditionalTrain
      params:
        data_path: data/augmented
    validation:
      target: ldm.data.cfd_data.CFDConditionalValidation
      params:
        data_path: data/augmented

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: False
        log_on_batch_idx: True

  trainer:
    benchmark: True
